<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.qiao</groupId>
        <artifactId>oa-cloud</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>oa-common</artifactId>
    <packaging>pom</packaging>
    <name>OA Common - 公共模块</name>

    <modules>
        <module>oa-common-core</module>
        <module>oa-common-redis</module>
        <module>oa-common-jwt</module>
        <module>oa-common-security</module>
        <module>oa-common-rabbitmq</module>
        <module>oa-common-mybatis</module>
    </modules>

</project>
